import Navbar from "@/components/navbar/Navbar"
import ToastProvider from "@/providers/ToastProvider"
import { cn } from "@/utils/utils"
import { ClerkProvider } from "@clerk/nextjs"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Footer from "@/components/footer/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={cn(
          "bg-white text-slate-900 antialiased light ",
          inter.className
        )}
      >
        <body className="min-h-[100vh] pt-12 bg-slate-50 antialiased flex flex-col">
          <ToastProvider />

          <Navbar />
          <div className="container max-w-7xl mx-auto h-full pt-12">
            {children}
          </div>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  )
}
